language: cpp
sudo: required
compiler: 
  - gcc
  - clang
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7


script:
  - $CXX --version
  - mkdir build && cd build && mkdir Debug && cmake .. --target ALL_BUILD
  - ctest -j10 -T test --output-on-failure
